name: 3c Compilation and Test Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup build directory and Compile 3c target
        run: |
          mkdir -p llvm/build
          cd llvm/build
          cmake -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_RUNTIMES=compiler-rt -DCMAKE_LINKER=/usr/bin/gold -DCMAKE_BUILD_TYPE=Debug -DLLVM_LIT_ARGS=-v -DLLVM_PARALLEL_LINK_JOBS=1 ../
          ninja 3c
          ninja checkcbox-headers # for the typeflexer headers
          echo "$PWD/bin" >> $GITHUB_PATH  # Assuming the 3c binary is located in ./llvm/build/bin after compilation

      - name: Create temp_output directory
        run: mkdir -p $GITHUB_WORKSPACE/typematic-tests/temp_output

      - name: Run 3c on nsimple.c and compare
        run: |
          cd $GITHUB_WORKSPACE/typematic-tests
          file=input/nsimple.c
          filename=$(basename -- "$file")
          base="${filename%.*}"
          3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          diff -w "temp_output/${base}.c" "output/${base}_expected.c"

      - name: Run 3c on simple.c and compare
        run: |
          cd $GITHUB_WORKSPACE/typematic-tests
          file=input/simple.c
          filename=$(basename -- "$file")
          base="${filename%.*}"
          3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          diff -w "temp_output/${base}.c" "output/${base}_expected.c"


      - name: Run 3c on structsimple_1.c and compare
        run: |
          cd $GITHUB_WORKSPACE/typematic-tests
          file=input/structsimple_1.c
          filename=$(basename -- "$file")
          base="${filename%.*}"
          3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          diff -w "temp_output/${base}.c" "output/${base}_expected.c"

      - name: Run 3c on structsimple_2.c and compare
        run: |
          cd $GITHUB_WORKSPACE/typematic-tests
          file=input/structsimple_2.c
          filename=$(basename -- "$file")
          base="${filename%.*}"
          3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          diff -w "temp_output/${base}.c" "output/${base}_expected.c"

      - name: Run 3c on structsimple.c and compare
        run: |
          cd $GITHUB_WORKSPACE/typematic-tests
          file=input/structsimple.c
          filename=$(basename -- "$file")
          base="${filename%.*}"
          3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          diff -w "temp_output/${base}.c" "output/${base}_expected.c"