name: 3c Compilation and Test Workflow

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup build directory and Compile 3c target
        run: |
          mkdir -p llvm/build
          cd llvm/build
          cmake -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_RUNTIMES=compiler-rt -DCMAKE_LINKER=/usr/bin/gold -DCMAKE_BUILD_TYPE=Debug -DLLVM_LIT_ARGS=-v -DLLVM_PARALLEL_LINK_JOBS=1 ../
          ninja 3c
          ninja checkcbox-headers # for the typeflexer headers
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Create temp_output directory
        run: mkdir -p $GITHUB_WORKSPACE/typematic-tests/temp_output

      - name: Define file check function
        run: |
          compare_files() {
            file="input/$1"
            filename=$(basename -- "$file")
            base="${filename%.*}"
            3c -addcr -alltypes "$file" -- > "temp_output/${base}.c"
          
            # Process both files to remove consecutive newlines
            awk 'NF || !seen[$0]++' "temp_output/${base}.c" > "temp_output/${base}_processed.c"
            awk 'NF || !seen[$0]++' "output/${base}_expected.c" > "output/${base}_expected_processed.c"
          
            # Compare the processed files
            diff -w "temp_output/${base}_processed.c" "output/${base}_expected_processed.c"
          }
          echo "compare_files" >> $GITHUB_ENV

      - name: Run 3c on nsimple.c and compare
        run: compare_files nsimple.c
        continue-on-error: true
        shell: bash

      - name: Run 3c on simple.c and compare
        run: compare_files simple.c
        continue-on-error: true
        shell: bash

      - name: Run 3c on structsimple_1.c and compare
        run: compare_files structsimple_1.c
        continue-on-error: true
        shell: bash

      - name: Run 3c on structsimple_2.c and compare
        run: compare_files structsimple_2.c
        continue-on-error: true
        shell: bash

      - name: Run 3c on structsimple.c and compare
        run: compare_files structsimple.c
        continue-on-error: true
        shell: bash
